### ISSUE TITLE
jQueryやanimationで動きをつける

### ISSUE THREAD

**Issue by kanae-chaika** [s-hashizume/company#5]
対象サイト：https://s-hashizume.github.io/company/index.html
元サイト：https://www.edge-intl.co.jp/

### やったこと
- スマホ版においてハンバーガーメニューをタップすると3本線から「×」に変形する
- スマホ版においてスクロールするとハンバーガーメニューが小さくなる
- Loadingアニメーションの表示
- スクロールするとheaderの「お問い合わせボタン」がheader内に収まる
- footerの矢印ボタンによってtopまでスムーズに遷移する
- メインビジュアルの画像が拡大しながらフェードアウトして次の画像に映り変わる
- ハンバーガーメニュー内のリストをアコーディオンメニュー化

**Comment by kanae-chaika** [comment]
メインビジュアル右側の画像↓を数枚、slick jsでfadeでスライドさせてみましょうか！

![スクリーンショット 2023-07-12 12 17 13](https://github.com/s-hashizume/company/assets/84834399/d145d345-28d8-49df-b227-0e43de267b50)

**Comment by s-hashizume** [comment]
@kanae-chaika 

対象サイト：https://s-hashizume.github.io/company/index.html
元サイト：https://www.edge-intl.co.jp/

## スマホ版においてハンバーガーメニューをタップすると3本線から「×」に変形する

<style.css>
```
    .nav_op .humberger-menu span {
        position: absolute;
        top: 50%;
        width: 38px;
    }/*幅を38pxにして上下中央に位置決めする*/

    .nav_op .humberger-menu span:nth-child(1) {
        transform: scale(-1, -1) rotate(45deg);/*scale(-1, -1)でx軸に反転とy軸に反転の動作が入った後、rotate(45deg)によって45度に回転する*/
        transition: 0.6s;
    }

    .nav_op .humberger-menu span:nth-child(2) {
        transform: scale(0);
        transition: 0.6s;
    }

    .nav_op .humberger-menu span:nth-child(3) {
        transform: scale(-1, -1) rotate(-45deg);/*-45度に回転する*/
        transition: 0.6s;
    }
```

**Comment by kanae-chaika** [comment]
@s-hashizume 
スレッドTOPの「やったこと」を編集できないでしょうか？

**Comment by s-hashizume** [comment]
@kanae-chaika 
これで合っていますでしょうか？

**Comment by kanae-chaika** [comment]
@s-hashizume 
はい！そういう感じで箇条書きにしてください。（コードは全部書かなくても見てほしいところだけでOK）
他の箇所も含め、動きをつけるのがひととおり終わったら確認します。

※もう終了していますが、
ヘッダーのお問合せの高さのアニメーション、
上へ戻るボタン
などもこのタスクなので、箇条書きに加えてください！

**Comment by s-hashizume** [comment]
@kanae-chaika 
承知致しました！

**Comment by kanae-chaika** [comment]
@s-hashizume 
ローディングも忘れずお願いします。

**Comment by s-hashizume** [comment]
@kanae-chaika 
はい！承知しました！

**Comment by s-hashizume** [comment]
@kanae-chaika 
お疲れ様です！
```
1 スマホ版においてハンバーガーメニューをタップすると3本線から「×」に変形する
2 スマホ版においてスクロールするとハンバーガーメニューが小さくなる
3 Loadingアニメーションの表示
4 スクロールするとheaderの「お問い合わせボタン」がheader内に収まる
5 footerの矢印ボタンによってtopまでスムーズに遷移する
6 メインビジュアルの画像が拡大しながらフェードアウトして次の画像に映り変わる
7 ハンバーガーメニュー内のリストをアコーディオンメニュー化
```
上記のanimation等が完了致しましたので、ご確認の程よろしくお願い致します！

**Comment by s-hashizume** [comment]
@kanae-chaika 

1 スマホ版においてハンバーガーメニューをタップすると3本線から「×」に変形する
2 スマホ版においてスクロールするとハンバーガーメニューが小さくなる
3 Loadingアニメーションの表示
4 スクロールするとheaderの「お問い合わせボタン」がheader内に収まる
5 footerの矢印ボタンによってtopまでスムーズに遷移する
6 メインビジュアルの画像が拡大しながらフェードアウトして次の画像に映り変わる
7 ハンバーガーメニュー内のリストをアコーディオンメニュー化

上記が完了致しましたのでご確認の程よろしくお願い致します！

**Comment by kanae-chaika** [comment]
@s-hashizume 
以下ご確認お願いします。
デザイン部分はもう少し細かく見て自分で気づけるようにしましょう！


### ハンバーガーメニュー

- [x] これは何のために入れていますか？
`$(this).parent().find('.header-nav__listLv2').addClass("hidden-list_open");`

- [x] タップした時に色が変わるのを無くしてください。実機ではグレーになる
https://github.com/s-hashizume/company/assets/84834399/b4fd5abf-6598-48e6-8a39-2a9ad0da44b0

- [x] スマホサイズによっては、矢印が右端にない

- [x] 閉じる時にファーストビューの文字が上に来る
https://github.com/s-hashizume/company/assets/84834399/4d0bea28-aa61-4375-a3bf-dd3042e4ed03

- [x] スクロールした時に3本線が中央にない
![スクリーンショット 2023-07-19 12 53 13](https://github.com/s-hashizume/company/assets/84834399/21758fcb-ed6f-4954-b515-9615ba3a1c98)


### メインビジュアル　

- [ ] PCで画像の位置が左に寄っている。中央になるように。coverは効いているか？
![スクリーンショット 2023-07-19 12 48 32](https://github.com/s-hashizume/company/assets/84834399/f51a2504-6e66-4f11-b694-a7549566c585)

- [x] スマホサイズによっては画像が右端に付かない。（もともとそうだったのかも）
![スクリーンショット 2023-07-19 12 47 13](https://github.com/s-hashizume/company/assets/84834399/cdb54679-3514-4af6-892b-f3057c31befb)


### 読み込み

- [x] jquery3を読み込んでいるのに2も読み込んでいるのはなぜか？
- [x] slickも2つ読み込まれている
- [x] 読み込み順がおかしい

![スクリーンショット 2023-07-19 12 58 43](https://github.com/s-hashizume/company/assets/84834399/53efdcd7-fec9-4378-9cb2-5cfe37d3c092)

**Comment by s-hashizume** [comment]
@kanae-chaika 
承知致しました！
修正いたします！

**Comment by s-hashizume** [comment]
@kanae-chaika 
修正が完了致しましたので、ご確認の程よろしくお願い致します!

### ハンバーガーメニュー

- [ ]  これは何のために入れていますか？

`$(this).parent().find('.header-nav__listLv2').addClass("hidden-list_open");`

→これは、`.header-nav__listLv2`にもともと`position: absolute;`が入っており、このままでは展開した時に高さがないので、クリックしたら`position: static;`になるようにすれば展開できると思いつきましたので入れました。

と思っていましたが、そもそもcssでレスポンシブ化させる時に指定してしまえば良いことに気づきました。最終的に↓

```css
----スマホ-----
   .header-nav__listLv2 {
        margin-top: 19px;
        position: static;
    }
```

- [ ] タップした時に色が変わるのを無くしてください。実機ではグレーになる
https://github.com/s-hashizume/company/assets/84834399/b4fd5abf-6598-48e6-8a39-2a9ad0da44b0
↓
```
---スマホ----  
  .header-wrapper-menu-button {
        display: flex;
        flex-direction: column;
        width: 100%;
        position: relative;
        align-items: baseline;
        -webkit-tap-highlight-color:rgba(0,0,0,0);　←
    }
```
上記により解消

- [ ]  スマホサイズによっては、矢印が右端にない

→.`header-wrapper-nav-list li`に`width: 100%;`を入れることで解消

- [ ]  閉じる時にファーストビューの文字が上に来る

→top画像の`.top-contents-wrap-character`に対して`z-index: -1;`を追加
文字部分の`.top-contents-wrap-character`の`z-index: 2;`を削除することで解消
不要となった`.nav_op .character`の指定は削除

- [ ]  スクロールした時に3本線が中央にない

↓

```css
.scrolled .humberger-menu span {
    left: calc(50% - 20px);
}
```

にすることで左右中央にした

### メインビジュアル

- [ ]  PCで画像の位置が左に寄っている。中央になるように。coverは効いているか？

→効いていなかったので、削除。

- [ ]  スマホサイズによっては画像が右端に付かない。

↓

```css
.top-contents-wrap-image {
    position: absolute;
    top: 0;
    left: 49%;
    overflow: hidden;
    width: 51.1111111111vw;
    height: auto;
    overflow: hidden;
    z-index: 1;
}

----スマホ----
  .top-contents-wrap-image {
        top: 144px;
        left: 116px;
        width: 258.641px;
        z-index: -1;
  }

```

上記のようになっていたのを

```css
@media (max-width: 820px) {
  .top-contents-wrap-image {
        top: 144px;
        left: auto;
        right: 0;
        width: 258.641px;
        z-index: -1;
    }
}
```

に変更で解消

### 読み込み

- [ ]  jquery3を読み込んでいるのに2も読み込んでいるのはなぜか？
- [ ]  slickも2つ読み込まれている
- [ ]  読み込み順がおかしい

→不要なものを整理

→調べながらやっている際にそのまま組み込みっぱなしになっていた為

**Comment by kanae-chaika** [comment]
@s-hashizume 

### ハンバーガーメニュー

>タップした時に色が変わるのを無くしてください。実機ではグレーになる

OKなのですが、他のaタグも同じことが起こる可能性があるので、aすべてに入れた方がいいと思います。

>スマホサイズによっては、矢印が右端にない
→.header-wrapper-nav-list liにwidth: 100%;を入れることで解消

矢印の位置変わっていません。（※画像1）

> 閉じる時にファーストビューの文字が上に来る
→top画像の.top-contents-wrap-characterに対してz-index: -1;を追加
文字部分の.top-contents-wrap-characterのz-index: 2;を削除することで解消
不要となった.nav_op .characterの指定は削除

`.top-contents-wrap-characterに対してz-index: -1;を追加`は無かったけど、できてるのでOK

> スクロールした時に3本線が中央にない
↓
.scrolled .humberger-menu span {
    left: calc(50% - 20px);
}

最初にleftのみ指定するから計算が必要になるんです。
下記のようにして、.scrolled .humberger-menu span の指定は外してください。
![スクリーンショット 2023-07-20 19 12 11](https://github.com/s-hashizume/company/assets/84834399/69fd2d7c-6066-4b84-810c-7fb23420c51b)

↓これでやったやつ。今回の場合、3つのどれでも使えます。
![スクリーンショット 2023-07-20 19 29 17](https://github.com/s-hashizume/company/assets/84834399/7cb687ef-e2c4-4564-b1a1-3d399e11ba2b)


ーーーー
前回気づいていなかったこと🙏

- [ ] 矢印の挙動も、元サイトと同じにしましょう。
コピーサイトは、
・開く時に矢印が一回縮む
・閉じる時にパキッと変わる
![スクリーンショット 2023-07-20 19 33 45](https://github.com/s-hashizume/company/assets/84834399/d2c7567e-067e-42c9-992d-e90650bec1d6)


- [ ] アコーディオン開いた時のデザインが少し違う
※画像1
![スクリーンショット 2023-07-20 18 50 11](https://github.com/s-hashizume/company/assets/84834399/f7df8b98-73de-4cb1-bec3-f4b5a54d2650)

### メインビジュアル

 >PCで画像の位置が左に寄っている。中央になるように。coverは効いているか？
→効いていなかったので、削除。

まだ寄っている。
左にというのは、left topに寄っているという意味。中央寄せにしてください。

![スクリーンショット 2023-07-20 18 45 43](https://github.com/s-hashizume/company/assets/84834399/23f84214-bcf6-4a36-a863-f16437c44549)
![スクリーンショット 2023-07-20 18 45 59](https://github.com/s-hashizume/company/assets/84834399/86e41125-8bd9-4591-ac86-207773bc580f)

![スクリーンショット 2023-07-20 18 46 20](https://github.com/s-hashizume/company/assets/84834399/893623f3-4525-474e-b08f-250a2f74ed0b)
![スクリーンショット 2023-07-20 18 46 04](https://github.com/s-hashizume/company/assets/84834399/26573e05-7d03-4039-a9aa-c2ac1a97865a)


ーーーー
前回気づいていなかったこと🙏

- [ ] 元サイトは、ローディング後に1枚目の画像から始まります
コピーサイトは2枚目の画像からしか見れません
調整しましょう！

ヒントコード
```
//1秒待つ
$(document).ready(function(){
$('.index_slide').slick({
autoplay: false,
dots: false,
fade: true,
speed: 1000
});
setTimeout( function(){
$('.index_slide').slick('play');
}, 1000);
});
```


以上です！

**Comment by s-hashizume** [comment]
@kanae-chaika 
ご指摘いただきました点について修正致しましたので確認のほど宜しくお願い致します！

## 修正内容

### ハンバーガーメニュー

- [ ]  タップした時に青くなるのは無くなったが、他のaタグも修正する

```css
/*--------<a>と<button>が青くなることが判明したので、---------------*/

a {
    text-decoration: none;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}

button {
    font-family: "Yu Gothic", YuGothic, "Hiragino Kaku Gothic ProN", "ヒラギノ角ゴ ProN", "メイリオ", "Meiryo", sans-serif;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}

/*-------と指定した-------*/
```

- [ ]  メニューリストの矢印の位置が違う（iPhone SE以外）
width: 100%;にしてSEでは揃ったが、それ以外では揃っていない
bottonの幅が異なっていた
ulとliに幅の差があった
liにwidth: 336px;が入っていた　←　これが原因

```css
.header-wrapper-nav-list li {
  width: 100%;
}

/*上記にして、SE以外で確認してOK*/
```

- [ ]  スクロールした時に三本線が中央に無い↓
最初にleftのみ指定するから計算が必要になるんです。.scrolled .humberger-menu span の指定は外してください。

---

1. `left: 0;`且つ`right: 0;`にすることでこのspanの範囲は親要素に対して幅いっぱいになる
2. `span`タグはインライン要素であるが`display: block;`の指定がなされている
3. `width`によって幅が指定されている
4. 上記２つによって`margin: 0 auto;`が実行可能となり`span`は親要素の左右中央に配置される

---

```css
.humberger-menu span {
    height: 1px;
    width: 2.5rem;
    background: #fff;
    display: block;
    position: absolute;
    top: calc(50% - 0.375rem);
    left: 0;
    right: 0;
    margin: 0 auto;
    transition: 0.3s;
}

/*他の機種でもOK*/
```

- [ ]  矢印の挙動の調整

１　開く時に矢印が一回縮む

```css

.list_op .menu-allow {
  transform: scale(-1, -1);
}

/*こうなっていた*/
/*これは垂直方向に反転且つ水平方向に反転となってしまっている*/

.list_op .menu-allow {
  transform: scale(1, -1);
}

/*こうすることで、横座標はそのままで、縦座標を反転させることができる*/
```

２　閉じる時にパキッと閉じてしまう

```css
/*現状だと*/

.list_op .menu-allow {
  transform: scale(1, -1);
  transition: 0.6s;
}

/*となっており.list_opが.menu-allowに追加された時、0.6秒掛けてアニメーションを実行するだけなので*/

.list_op .menu-allow {
  transform: scale(1, -1);
  transition: 0.3s;
}

.menu-allow {
  transition: 0.3s;
}

/*.menu-allow自体にtransitionを付与した*/
/*また、本物とかかる時間が違ったので調整した*/
```

- [ ]  アコーディオンメニューのデザインが少し違う

→　アコーディオンリストにアンダーラインがある

```css
/*もともとが*/
.header-nav__listLv2 li {
    width: 220px;
    border-bottom: 1px solid #F0F4F8;
}

/*となっていたので、border-bottomがいらないので*/

.header-nav__listLv2 li {
    border-bottom: none;
}

/*とした　*/
```

## メインビジュアル

- [ ]  top画像を左上によっているのを中央寄せにする

```css
/*jQueryを一旦停止し、現状を確認すると本物と比較して画像が左上つきに且つ拡大しているように見えたので、サイズを確認すると、大きすぎることがわかったので*/

.top-images-pic img {
    width: 100%;
}

/*として静止状態と、jQuery付与状態で確認して中央に来たことを確認*/
```

- [ ]  ローディング後に１枚目の画像から始めるようにする（現段階では２枚目から始まっている）

**原因　→　「Loading」が表示されている間にもスライドが動作し続けているため**

- 「Loading」が表示されてからフェードアウトしきる時間合計7.5秒（4.5秒間完全にLoading画面で、その後3.0秒かけて薄れていく）
- top画像が完全に入れ替わる時間合計4.5秒

ということから、「Loading」が終了する頃には２枚目に移行していることがわかる

→ よって、解決策としてスライド開始時間を遅らせることで１枚目から表示させることができる

実行を遅らせるには、`setTimeout`メソッドを使用できる

第一引数に処理内容、第二引数に遅延時間をミリ秒で指定できる↓

```css
setTimeout(function(){
    const $slide = $(".change-slides")
    .slick({
        fade: true,    // fedeオン
        speed: 1500,   // 画像切り替えにかかる時間（ミリ秒）
        autoplaySpeed: 3000,   // 自動スライド切り替え速度
        arrows: false,         // 矢印表示・非表示
        autoplay: true,        // 自動再生
        slidesToShow: 1,       // スライド表示数
        slidesToScroll: 1,     // スライドする数
        infinite: true         // 無限リピート オン・オフ
    })
    .on({
        beforeChange: function(event, slick, currentSlide, nextSlide) {
            $(".slick-slide", this).eq(currentSlide).addClass("preve-slide");
            $(".slick-slide", this).eq(nextSlide).addClass("slide-animation");
        },
        afterChange: function() {
            $(".preve-slide", this).removeClass("preve-slide slide-animation");
        }
    });
    $slide.find(".slick-slide").eq(0).addClass("slide-animation");
}, 4500);
```

**Comment by kanae-chaika** [comment]
@s-hashizume 

> ### ハンバーガーメニュー
> * [ ]   タップした時に青くなるのは無くなったが、他のaタグも修正する
> 
> ```css
> /*--------<a>と<button>が青くなることが判明したので、---------------*/
> 
> a {
>     text-decoration: none;
>     -webkit-tap-highlight-color: rgba(0,0,0,0);
> }
> 
> button {
>     font-family: "Yu Gothic", YuGothic, "Hiragino Kaku Gothic ProN", "ヒラギノ角ゴ ProN", "メイリオ", "Meiryo", sans-serif;
>     -webkit-tap-highlight-color: rgba(0,0,0,0);
> }
> 
> /*-------と指定した-------*/
> ```
 
OKです！
が、.header-wrapper-menu-button の -webkit-tap-highlight-colorが重複してるので削除してください。

あと、bottonのfont-familyは削除したんじゃなかったですっけ？bodyにYu Gothic指定されてるので削除してください。

![スクリーンショット 2023-07-21 14 14 56](https://github.com/s-hashizume/company/assets/84834399/84bb9fb8-ea19-473b-865d-a389a53524e1)



> * [ ]   メニューリストの矢印の位置が違う（iPhone SE以外）
>   width: 100%;にしてSEでは揃ったが、それ以外では揃っていない
>   bottonの幅が異なっていた
>   ulとliに幅の差があった
>   liにwidth: 336px;が入っていた　←　これが原因
> 
> ```css
> .header-wrapper-nav-list li {
>   width: 100%;
> }
> 
> /*上記にして、SE以外で確認してOK*/
> ```

厳密に言うと、上記のwidthは不要です。flexのcolumnの子要素だから。
ちなみに下のメディアクエリの中のdisplay: flex;も重複していて不要です。

![スクリーンショット 2023-07-21 14 26 42](https://github.com/s-hashizume/company/assets/84834399/adc466c7-dbfb-4648-bee4-8725a4e547ba)

必要なのはこちら↓のみです。（PCで指定したwidthの解除。もう入ってる。）
```
@media (max-width: 744px) {
.header-nav__listLv2 li {
    width: 100%;
}
}
```


> * [ ]   スクロールした時に三本線が中央に無い↓
>   最初にleftのみ指定するから計算が必要になるんです。.scrolled .humberger-menu span の指定は外してください。
> 
> 1. `left: 0;`且つ`right: 0;`にすることでこのspanの範囲は親要素に対して幅いっぱいになる
> 2. `span`タグはインライン要素であるが`display: block;`の指定がなされている
> 3. `width`によって幅が指定されている
> 4. 上記２つによって`margin: 0 auto;`が実行可能となり`span`は親要素の左右中央に配置される
> 
> ```css
> .humberger-menu span {
>     height: 1px;
>     width: 2.5rem;
>     background: #fff;
>     display: block;
>     position: absolute;
>     top: calc(50% - 0.375rem);
>     left: 0;
>     right: 0;
>     margin: 0 auto;
>     transition: 0.3s;
> }
> 
> /*他の機種でもOK*/
> ```

→OK！

> * [ ]   矢印の挙動の調整
> 
> １　開く時に矢印が一回縮む
> 
> ```css
> .list_op .menu-allow {
>   transform: scale(-1, -1);
> }
> 
> /*こうなっていた*/
> /*これは垂直方向に反転且つ水平方向に反転となってしまっている*/
> 
> .list_op .menu-allow {
>   transform: scale(1, -1);
> }
> 
> /*こうすることで、横座標はそのままで、縦座標を反転させることができる*/
> ```
> 

→OK！

> ２　閉じる時にパキッと閉じてしまう
> 
> ```css
> /*現状だと*/
> 
> .list_op .menu-allow {
>   transform: scale(1, -1);
>   transition: 0.6s;
> }
> 
> /*となっており.list_opが.menu-allowに追加された時、0.6秒掛けてアニメーションを実行するだけなので*/
> 
> .list_op .menu-allow {
>   transform: scale(1, -1);
>   transition: 0.3s;
> }
> 
> .menu-allow {
>   transition: 0.3s;
> }
> 
> /*.menu-allow自体にtransitionを付与した*/
> /*また、本物とかかる時間が違ったので調整した*/
> ```

→OKだけど、
.list_op .menu-allow のtransitionは重複しているので不要！
![スクリーンショット 2023-07-21 14 11 39](https://github.com/s-hashizume/company/assets/84834399/ab155cc0-01c8-4d5a-9d1a-725f33e8d96f)


> 
> * [ ]   アコーディオンメニューのデザインが少し違う
> 
> →　アコーディオンリストにアンダーラインがある
> 
> ```css
> /*もともとが*/
> .header-nav__listLv2 li {
>     width: 220px;
>     border-bottom: 1px solid #F0F4F8;
> }
> 
> /*となっていたので、border-bottomがいらないので*/
> 
> .header-nav__listLv2 li {
>     border-bottom: none;
> }
> 
> /*とした　*/
> ```

→OK！


> ## メインビジュアル
> * [ ]   top画像を左上によっているのを中央寄せにする
> 
> ```css
> /*jQueryを一旦停止し、現状を確認すると本物と比較して画像が左上つきに且つ拡大しているように見えたので、サイズを確認すると、大きすぎることがわかったので*/
> 
> .top-images-pic img {
>     width: 100%;
> }
> 
> /*として静止状態と、jQuery付与状態で確認して中央に来たことを確認*/
> ```
> 

ひとつクリアです。
現状、あきらかに画像がへしゃげてるので、object-fitを使用しましょう！
参考　https://localhost8888.net/css/260/
![スクリーンショット 2023-07-21 14 43 34](https://github.com/s-hashizume/company/assets/84834399/7a1589ac-d749-4b6f-8719-ce0c25bf0aa3)


> * [ ]   ローディング後に１枚目の画像から始めるようにする（現段階では２枚目から始まっている）
> 
> **原因　→　「Loading」が表示されている間にもスライドが動作し続けているため**
> 
> * 「Loading」が表示されてからフェードアウトしきる時間合計7.5秒（4.5秒間完全にLoading画面で、その後3.0秒かけて薄れていく）
> * top画像が完全に入れ替わる時間合計4.5秒
> 
> ということから、「Loading」が終了する頃には２枚目に移行していることがわかる
> 
> → よって、解決策としてスライド開始時間を遅らせることで１枚目から表示させることができる
> 
> 実行を遅らせるには、`setTimeout`メソッドを使用できる
> 
> 第一引数に処理内容、第二引数に遅延時間をミリ秒で指定できる↓
> 
> ```css
> setTimeout(function(){
>     const $slide = $(".change-slides")
>     .slick({
>         fade: true,    // fedeオン
>         speed: 1500,   // 画像切り替えにかかる時間（ミリ秒）
>         autoplaySpeed: 3000,   // 自動スライド切り替え速度
>         arrows: false,         // 矢印表示・非表示
>         autoplay: true,        // 自動再生
>         slidesToShow: 1,       // スライド表示数
>         slidesToScroll: 1,     // スライドする数
>         infinite: true         // 無限リピート オン・オフ
>     })
>     .on({
>         beforeChange: function(event, slick, currentSlide, nextSlide) {
>             $(".slick-slide", this).eq(currentSlide).addClass("preve-slide");
>             $(".slick-slide", this).eq(nextSlide).addClass("slide-animation");
>         },
>         afterChange: function() {
>             $(".preve-slide", this).removeClass("preve-slide slide-animation");
>         }
>     });
>     $slide.find(".slick-slide").eq(0).addClass("slide-animation");
> }, 4500);
> ```

→ヒントコードの書き方の方がスマートなんだけど、まあいいでしょう！

**Comment by s-hashizume** [comment]
@kanae-chaika 
ご確認の程ありがとうございます！
確認の後、修正いたします！

**Comment by s-hashizume** [comment]
@kanae-chaika 

指摘事項修正完了につき確認のほど宜しくお願い致します！

# 修正内容

- [ ]  .header-wrapper-menu-button の -webkit-tap-highlight-colorが重複してるので削除してください

```css

button {
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}

---スマホ---
.header-wrapper-menu-button {
        display: flex;
        flex-direction: column;
        width: 100%;
        position: relative;
        align-items: baseline;
}
```

- [ ]  widthは不要です。メディアクエリの中のdisplay: flex;も重複していて不要です。

```css
.header-wrapper-nav-list li {
        background: #fff;
}

.header-wrapper-nav-list {
        flex-direction: column;
        gap: 30px;
}

.header-nav__listLv2 li {
        border-bottom: none;
        width: 100%;
}/*PC版のwidthが適用されてしまうため*/
```

- [ ]  .list_op .menu-allow のtransitionは重複しているので不要

```css
.list_op .menu-allow {
        transform: scale(1, -1);
}

.menu-allow {
        transition: 0.3s;
}
```

- [ ]  現状、あきらかに画像がへしゃげてるので、object-fitを使用しましょう

```css
.top-images-pic img {
    width: 100%;
    object-fit: cover;
}
```
